# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25d88de8c32b50dfb768c0fc23e0ff87c9d87d08449f111c0cb7a836f35c0412733ff171d05b00678432f24a7f8ba4ec0106b13ecadb44c0054ee84d486d47cf

test:
  secret_key_base: 01fd45077abd555d00a4532a4b5592825100ad8b3bd8b8bfa459a0a52a6b0d0745b06320d327c3292af498834ce4c52192bf38cb250e3c9df5d1738a98e3a6ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
